services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - mongo-database
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: monogo-ui
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
    ports:
      - 8080:8081
    networks:
      - mongo-database

networks:
  mongo-database:
    driver: bridge

volumes:
  mongo-data:
